version: '3'
services:
  postgres:
    image: 'postgres:14.4'
    container_name: "postgresql"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=bank_egar'
      - 'POSTGRES_PASSWORD=123456'
    ports:
      - "5433:5432"

  app:
    build: ./
    container_name: 'bank_app'
    environment:
      - 'PORT=8080'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/bank_egar'
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'



